#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected="$1"
else
	selected=$(find -L ~/ ~/projects ~/curtin ~/curtin/teaching -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z "$selected" ]]; then
	exit 0
fi

if [[ "$selected" = "$HOME" ]]; then
	selected_name='~'
else
	selected_name=$(basename "$selected" | tr \ . _)
fi

tmux_running=$(pgrep tmux 2>/dev/null)

if [[ (-z $TMUX) && (-z $tmux_running) ]]; then
	tmux new-session -c "$selected" -s "$selected_name"
else
	if ! tmux has-session -t "$selected_name" 2>/dev/null; then
		tmux new-session -c "$selected" -ds "$selected_name"
	fi

	tmux switch-client -t "$selected_name"
fi
